name = "lbp_desugaring"
version = "1.0.0"

[dependencies]
blamedlines = { "path" = "../../vistuleB/blamedlines" }
vxml_parser = { "path" = "../../vistuleB/vxml_parser" }
writerly_parser = { "path" = "../../vistuleB/writerly_parser" }

gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleescript = ">= 1.4.0 and < 2.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
xmlm = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
